<a href="https://colab.research.google.com/github/zohaib166/python_general/blob/main/Python_Unit_II_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
## Ways to create numpy arrays

In [1]:
import numpy as np
mylist = [2,3,4,5,6]
myarray = np.array(mylist)
print(myarray)
print(type(myarray))


[2 3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
arr1 = np.arange(0,20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
print(arr1.shape)

(20,)


In [4]:
arr2 = np.reshape(arr1,(5,4))
print(arr2)
print(arr2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [5]:
arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr4 = np.ones((4,5),np.int8)
print(arr4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
arr5 = np.eye(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
print(np.full((2,3),6))

[[6 6 6]
 [6 6 6]]


In [9]:
arr6 = np.linspace(1,5,10)
print(arr6)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [10]:
# Do not include last sample
arr6 = np.linspace(1,5,10,False)
print(arr6)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [11]:
# Get stepsize
arr6 = np.linspace(start = 1, stop = 5, num = 10, endpoint = True, retstep = True)
print(arr6)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [12]:
# array of random numbers
arr7 = np.random.rand(5)
print(arr7)

[0.01720728 0.31236893 0.170079   0.99840774 0.10509677]


In [13]:
arr7 = np.random.rand(5,5)
print(arr7)

[[0.95613752 0.73212848 0.27794731 0.98982285 0.01429788]
 [0.33376356 0.69053817 0.32059429 0.17131645 0.80518318]
 [0.96341763 0.18855442 0.8644149  0.34075408 0.75088386]
 [0.02816648 0.71553065 0.51222769 0.0701749  0.85012554]
 [0.61872171 0.90797738 0.32167973 0.79929186 0.32984931]]


In [14]:
arr7 = np.random.randn(5,5)
print(arr7)

[[ 0.14584286  0.05236307  0.63375189 -0.5523962   0.93049884]
 [ 2.53264331 -0.31292748 -0.12199948  1.39998557 -1.11161402]
 [-1.19133587 -0.59813198 -0.33585204 -0.42201212 -0.09869914]
 [ 0.48500788 -1.90559925 -0.74998668  0.44340207  1.15440568]
 [-0.09209634  2.29018496 -0.90077591 -0.54174176  1.61412441]]


In [15]:
arr7 = np.random.randint(1,100,(4,3))
print(arr7)

[[54 95 13]
 [80  6 83]
 [79 37 75]
 [ 8 90 49]]


In [16]:
print(arr7.max())
print(arr7.min())
print(arr7.argmax()) #index having max
print(arr7.argmin()) #index having min
print(arr7.shape)

95
6
1
4
(4, 3)


In [17]:
print(arr7.ndim) #tells the dimensions of an array

2


In [18]:
arr7 = arr7.reshape(-1,12)
print(arr7)

[[54 95 13 80  6 83 79 37 75  8 90 49]]


In [19]:
x = [1,2,3,4]
y = [10,20,30,40]
z = [11, 22, 33, 44]
mul_arr = np.array([x,y,z])
print(mul_arr.shape)

(3, 4)


In [20]:
print(mul_arr.reshape(1,12))

[[ 1  2  3  4 10 20 30 40 11 22 33 44]]


In [21]:
num1 = np.array([[1,2,3],[4,5,6]])
num2 = np.array([[7,8,9],[10,20,30]])

## Numpy Operations

In [22]:
print(num2-num1)

[[ 6  6  6]
 [ 6 15 24]]


In [23]:
print(num2+num1)

[[ 8 10 12]
 [14 25 36]]


In [24]:
print(num2*num1)

[[  7  16  27]
 [ 40 100 180]]


In [25]:
print(num1.dot(num2.transpose()))

[[ 50 140]
 [122 320]]


In [26]:
print(num2 / num1)

[[7.  4.  3. ]
 [2.5 4.  5. ]]


## Array slicing and indexing

In [27]:
arr8 = np.random.randint(1,20,10)
print(arr8)

[ 2  3  1  6  6 17  1 15 10 19]


In [28]:
arr9 = arr8[0:5]
print(arr9)

[2 3 1 6 6]


In [29]:
arr9[:] = 5

In [30]:
print(arr8)

[ 5  5  5  5  5 17  1 15 10 19]


In [31]:
arr8_copy = arr8.copy()
arr8_slice = arr8_copy[0:6]

In [32]:
arr8_slice[:] = 8

In [33]:
print(arr8)

[ 5  5  5  5  5 17  1 15 10 19]


In [34]:
print(num1)
print(num1[0,2])

[[1 2 3]
 [4 5 6]]
3


In [35]:
print(num1[0,:])

[1 2 3]


In [36]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## Numpy Functions

In [37]:
np.sum(arr_2d)

1225

In [38]:
np.sum(arr_2d, axis = 0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [39]:
np.sum(arr_2d, axis = 1)

array([ 45, 145, 245, 345, 445])

In [40]:
print(arr_2d[1:3,4:6])

[[14 15]
 [24 25]]


In [41]:
num4 = np.arange(1,10)
print(num4)

[1 2 3 4 5 6 7 8 9]


In [42]:
print(num4**2)

[ 1  4  9 16 25 36 49 64 81]


In [43]:
print(np.sqrt(num4))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [44]:
print(np.exp(num4))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [56]:
mat = np.arange(1,10,1).reshape(3,3)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
mat = np.transpose(mat)
print(mat)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [64]:
np.append(mat, [[10,11,12]], axis = 0)

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [10, 11, 12]])

In [77]:
col = np.transpose([[11,22,33]])
print(col)
np.append(mat,col,axis=1)

[[11]
 [22]
 [33]]


array([[ 1,  4,  7, 11],
       [ 2,  5,  8, 22],
       [ 3,  6,  9, 33]])

In [75]:
print(mat)
np.insert(mat, 1, [10,11,12], axis = 0)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[ 1,  4,  7],
       [10, 11, 12],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [74]:
print(mat)
np.insert(mat, 1, [10,11,12], axis = 1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[ 1, 10,  4,  7],
       [ 2, 11,  5,  8],
       [ 3, 12,  6,  9]])

In [80]:
np.delete(mat,0,axis=0)

array([[2, 5, 8],
       [3, 6, 9]])

In [82]:
np.delete(mat,1,1)

array([[1, 7],
       [2, 8],
       [3, 9]])

# Pandas

## Reading data from files into dataframes


In [93]:
import pandas as pd
import numpy as np

flower_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IRIS.csv")
print(flower_df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [84]:
flower_excel = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/IRIS_Excel.xlsx",sheet_name="IRIS")
print(flower_excel)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [85]:
flower_table = pd.read_table("/content/drive/MyDrive/Colab Notebooks/IRIS_txt.txt", sep="\t")
print(flower_table)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


## Dataframe

In [94]:
flower = flower_df.copy()

In [96]:
# get the range of index
print(flower.index)

RangeIndex(start=0, stop=150, step=1)


In [97]:
# get the names of all the columns
print(flower.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [98]:
# get total element count
print(flower.size)

750


In [99]:
# get the dimension of the data frame
print(flower.shape)

(150, 5)


In [101]:
# get the memory usage of each column in bytes
print(flower.memory_usage())

Index            128
sepal_length    1200
sepal_width     1200
petal_length    1200
petal_width     1200
species         1200
dtype: int64


In [102]:
# print first n rows of the dataframe
flower.head(5)

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [103]:
# print last n rows of the data frame
flower.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

## Accessing data from a dataframe

In [105]:
# access an entry in a dataframe
flower.at[145,'sepal_length']

6.7

In [108]:
# access an entry in a dataframe using integer based indexing
flower.iat[96,3]

1.3

In [110]:
#access a group of rows and columns
flower.loc[:,"sepal_width"]

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [112]:
#access a group of rows and columns
flower.loc[5:20,:]

sepal_length  sepal_width  petal_length  petal_width      species
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
15           5.7          4.4           1.5          0.4  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa
18           5.7          3.8           1.7          0.3  Iris-setosa
19           5.1          3.8           1.5          0.3  Iris-setosa
20           5.4          3.4           1.7          0.2  Iris-setosa

In [116]:
#check datatypes in dataframe
flower.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [119]:
# get a summarised info about the dataframe
flower.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [122]:
np.unique(flower['species'])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)