<a href="https://colab.research.google.com/github/zohaib166/python_general/blob/main/Python_Unit_II_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy
## Ways to create numpy arrays

In [2]:
import numpy as np
mylist = [2,3,4,5,6]
myarray = np.array(mylist)
print(myarray)
print(type(myarray))


[2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
arr1 = np.arange(0,20)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
print(arr1.shape)

(20,)


In [5]:
arr2 = np.reshape(arr1,(5,4))
print(arr2)
print(arr2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [6]:
arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr4 = np.ones((4,5),np.int8)
print(arr4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
arr5 = np.eye(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [56]:
print(np.full((2,3),6))

[[6 6 6]
 [6 6 6]]


In [9]:
arr6 = np.linspace(1,5,10)
print(arr6)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [10]:
# Do not include last sample
arr6 = np.linspace(1,5,10,False)
print(arr6)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [11]:
# Get stepsize
arr6 = np.linspace(start = 1, stop = 5, num = 10, endpoint = True, retstep = True)
print(arr6)

(array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]), 0.4444444444444444)


In [12]:
# array of random numbers
arr7 = np.random.rand(5)
print(arr7)

[0.84080654 0.1753416  0.40182276 0.94523449 0.68428194]


In [13]:
arr7 = np.random.rand(5,5)
print(arr7)

[[0.1248977  0.85700875 0.36465163 0.96233748 0.75823479]
 [0.94334506 0.47610409 0.10513263 0.27385381 0.58855681]
 [0.4369961  0.42282205 0.52287946 0.93883906 0.88623907]
 [0.95808669 0.11901296 0.33138329 0.36979575 0.87229475]
 [0.19760592 0.993187   0.96118437 0.94545123 0.80179357]]


In [14]:
arr7 = np.random.randn(5,5)
print(arr7)

[[ 0.46852653  0.57622725  0.24706835 -0.93896344  1.04836845]
 [-0.91060708 -0.7416739   0.07835552  0.22039461 -0.61767095]
 [ 0.19544767 -0.2585816   0.2925218  -1.95941846 -0.97246312]
 [ 0.10896927  0.82947781 -0.2751646  -0.33696466 -0.28871275]
 [-2.14231977 -0.23267705  0.41894785  0.9513505   3.75518276]]


In [15]:
arr7 = np.random.randint(1,100,(4,3))
print(arr7)

[[38 13 13]
 [80  8 74]
 [77 29  7]
 [11 57 26]]


In [16]:
print(arr7.max())
print(arr7.min())
print(arr7.argmax()) #index having max
print(arr7.argmin()) #index having min
print(arr7.shape)

80
7
3
8
(4, 3)


In [18]:
print(arr7.ndim) #tells the dimensions of an array

2


In [21]:
arr7 = arr7.reshape(-1,12)
print(arr7)

[[38 13 13 80  8 74 77 29  7 11 57 26]]


In [23]:
x = [1,2,3,4]
y = [10,20,30,40]
z = [11, 22, 33, 44]
mul_arr = np.array([x,y,z])
print(mul_arr.shape)

(3, 4)


In [25]:
print(mul_arr.reshape(1,12))

[[ 1  2  3  4 10 20 30 40 11 22 33 44]]


In [26]:
num1 = np.array([[1,2,3],[4,5,6]])
num2 = np.array([[7,8,9],[10,20,30]])

## Numpy Operations

In [31]:
print(num2-num1)

[[ 6  6  6]
 [ 6 15 24]]


In [30]:
print(num2+num1)

[[ 8 10 12]
 [14 25 36]]


In [32]:
print(num2*num1)

[[  7  16  27]
 [ 40 100 180]]


In [34]:
print(num1.dot(num2.transpose()))

[[ 50 140]
 [122 320]]


In [35]:
print(num2 / num1)

[[7.  4.  3. ]
 [2.5 4.  5. ]]


## Array slicing and indexing

In [37]:
arr8 = np.random.randint(1,20,10)
print(arr8)

[ 9  7 12 13 18  7  7 11 13  3]


In [39]:
arr9 = arr8[0:5]
print(arr9)

[ 9  7 12 13 18]


In [40]:
arr9[:] = 5

In [41]:
print(arr8)

[ 5  5  5  5  5  7  7 11 13  3]


In [42]:
arr8_copy = arr8.copy()
arr8_slice = arr8_copy[0:6]

In [43]:
arr8_slice[:] = 8

In [46]:
print(arr8)

[ 5  5  5  5  5  7  7 11 13  3]


In [50]:
print(num1)
print(num1[0,2])

[[1 2 3]
 [4 5 6]]
3


In [51]:
print(num1[0,:])

[1 2 3]


In [61]:
arr_2d = np.arange(50).reshape(5,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## Numpy Functions

In [62]:
np.sum(arr_2d)

1225

In [63]:
np.sum(arr_2d, axis = 0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [64]:
np.sum(arr_2d, axis = 1)

array([ 45, 145, 245, 345, 445])

In [66]:
print(arr_2d[1:3,4:6])

[[14 15]
 [24 25]]


In [72]:
num4 = np.arange(1,10)
print(num4)

[1 2 3 4 5 6 7 8 9]


In [73]:
print(num4**2)

[ 1  4  9 16 25 36 49 64 81]


In [74]:
print(np.sqrt(num4))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [75]:
print(np.exp(num4))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


# Pandas

## Reading data from files into dataframes


In [84]:
import pandas as pd
import numpy as np

flower_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/IRIS.csv",index_col = 0)
print(flower_df)

              sepal_width  petal_length  petal_width         species
sepal_length                                                        
5.1                   3.5           1.4          0.2     Iris-setosa
4.9                   3.0           1.4          0.2     Iris-setosa
4.7                   3.2           1.3          0.2     Iris-setosa
4.6                   3.1           1.5          0.2     Iris-setosa
5.0                   3.6           1.4          0.2     Iris-setosa
...                   ...           ...          ...             ...
6.7                   3.0           5.2          2.3  Iris-virginica
6.3                   2.5           5.0          1.9  Iris-virginica
6.5                   3.0           5.2          2.0  Iris-virginica
6.2                   3.4           5.4          2.3  Iris-virginica
5.9                   3.0           5.1          1.8  Iris-virginica

[150 rows x 4 columns]


In [88]:
flower_excel = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/IRIS_Excel.xlsx",sheet_name="IRIS")
print(flower_excel)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [90]:
flower_table = pd.read_table("/content/drive/MyDrive/Colab Notebooks/IRIS_txt.txt", sep="\t")
print(flower_table)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]
